project_name: hsctl

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./main.go
    binary: hsctl
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/obay/hsctl/cmd.version={{.Version}} -X github.com/obay/hsctl/cmd.commit={{.Commit}} -X github.com/obay/hsctl/cmd.buildDate={{.Date}}

archives:
  # Versioned archives (standard)
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_{{ .Version }}"
    files:
      - README.md
      - LICENSE
    format_overrides:
      - goos: windows
        format: zip
  # Version-less archives for easier direct downloads via /latest/download/
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: obay
    name: hsctl
  mode: replace
  header: |
    ## What's Changed
  footer: |
    **Full Changelog**: https://github.com/obay/hsctl/compare/{{ .PreviousTag }}...{{ .Tag }}

scoop:
  bucket:
    owner: obay
    name: scoop-bucket
  homepage: "https://github.com/obay/hsctl"
  description: "A CLI tool for managing HubSpot contacts"
  license: "MIT"
  persist:
    - config
  skip_upload: false

brews:
  - name: hsctl
    tap:
      owner: obay
      name: homebrew-tap
    homepage: "https://github.com/obay/hsctl"
    description: "A CLI tool for managing HubSpot contacts"
    license: "MIT"
    test: |
      system "#{bin}/hsctl --version"
    install: |
      bin.install "hsctl"

nfpms:
  - id: default
    package_name: hsctl
    maintainer: "obay <your-email@example.com>"
    description: "A CLI tool for managing HubSpot contacts"
    homepage: "https://github.com/obay/hsctl"
    license: "MIT"
    formats:
      - deb
      - rpm
    bindir: /usr/bin

